spring.application.name=academix_fw
spring.datasource.url=jdbc:postgresql://localhost:5432/juridico_db
spring.datasource.username=postgres
spring.datasource.password=postgre


spring.jpa.hibernate.ddl-auto=update
# Exibe o SQL no console para você conferir a mágica acontecendo
spring.jpa.show-sql=true
spring.profiles.include=secret